// <auto-generated />
using System;
using CovidStats.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidStats.Migrations
{
    [DbContext(typeof(CovidStatsDataContext))]
    partial class CovidStatsDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CovidStats.AccessData.Bezirk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BundeslandId")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BundeslandId");

                    b.ToTable("Bezirks");
                });

            modelBuilder.Entity("CovidStats.AccessData.Bundesland", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CasesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CasesId");

                    b.ToTable("Bundeslands");
                });

            modelBuilder.Entity("CovidStats.AccessData.Cases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BezirkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("Infections")
                        .HasColumnType("int");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyIncidents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BezirkId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CovidStats.AccessData.Bezirk", b =>
                {
                    b.HasOne("CovidStats.AccessData.Bundesland", "Bundesland")
                        .WithMany("Bezirke")
                        .HasForeignKey("BundeslandId");

                    b.Navigation("Bundesland");
                });

            modelBuilder.Entity("CovidStats.AccessData.Bundesland", b =>
                {
                    b.HasOne("CovidStats.AccessData.Cases", "Cases")
                        .WithMany()
                        .HasForeignKey("CasesId");

                    b.Navigation("Cases");
                });

            modelBuilder.Entity("CovidStats.AccessData.Cases", b =>
                {
                    b.HasOne("CovidStats.AccessData.Bezirk", "Bezirk")
                        .WithMany("Cases")
                        .HasForeignKey("BezirkId");

                    b.Navigation("Bezirk");
                });

            modelBuilder.Entity("CovidStats.AccessData.Bezirk", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("CovidStats.AccessData.Bundesland", b =>
                {
                    b.Navigation("Bezirke");
                });
#pragma warning restore 612, 618
        }
    }
}
